"""add is_done column

Revision ID: 751bcec8a693
Revises: 
Create Date: 2026-09-17 19:21:47.887154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '751bcec8a693'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The original autogenerated version used alter_column, which assumes
    # is_done already exists — that fails with "column does not exist" on
    # any database that hasn't had it created some other way. Use
    # add_column so this migration works from a clean database too.
    op.add_column(
        'orders',
        sa.Column('is_done', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('orders', 'is_done')
